[package]
name = "polkadot-erasure-coding"
version = "1.0.0"
description = "Erasure coding used for Polkadot's availability system"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# novelpoly = { git = "https://github.com/paritytech/reed-solomon-novelpoly.git", package = "reed-solomon-novelpoly" }
novelpoly = { path = "/home/alin/code/reed-solomon-novelpoly/reed-solomon-novelpoly", package = "reed-solomon-novelpoly" }

polkadot-primitives = { path = "../primitives" }
polkadot-node-primitives = { package = "polkadot-node-primitives", path = "../node/primitives" }
# novelpoly = { package = "reed-solomon-novelpoly", path = "/Users/alindima/Desktop/code/reed-solomon-novelpoly/reed-solomon-novelpoly"}
# "avx",
#]
parity-scale-codec = { version = "3.6.1", default-features = false, features = [
    "std",
    "derive",
] }
sp-core = { path = "../../substrate/primitives/core" }
sp-trie = { path = "../../substrate/primitives/trie" }
thiserror = "1.0.48"

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false, features = [
    "cargo_bench_support",
] }
quickcheck = { version = "1.0.3", default-features = false }

[[bench]]
name = "scaling_with_validators"
harness = false
